[pytest]
# addopts задает дефолтные аргументы запуска
# --headless отключен локально через --headed для удобной отладки в PyCharm
addopts = --alluredir=allure-results --clean-alluredir --browser=chromium --headed

# Явно указываем единственную директорию с тестами
testpaths = tests

# Регистрируем маркеры, чтобы pytest не выдавал предупреждения (warnings)
markers =
    smoke: критические тесты для проверки базовой работоспособности
    regression: регрессионные тесты
