[pytest]
# Оставляем только настройки Allure отчетов и выбор браузера по умолчанию
addopts = --alluredir=allure-results --clean-alluredir --browser=chromium
testpaths = tests
markers =
    smoke: критические тесты для проверки базовой работоспособности
    regression: регрессионные тесты
