[pytest]
# addopts задает дефолтные аргументы запуска
# --alluredir указывает, куда складывать сырые результаты Allure
# --clean-alluredir очищает прошлые результаты перед новым запуском
# --headed запускает браузер с графическим интерфейсом (удобно для локальной отладки, для CI потом уберем)
addopts = --alluredir=allure-results --clean-alluredir --browser=chromium --headed
testpaths = tests
markers =
    smoke: критические тесты для проверки базовой работоспособности
    regression: регрессионные тесты


# Явно указываем директорию с тестами
testpaths = tests

# Регистрируем кастомные маркеры (чтобы pytest не ругался на ворнинги)
markers =
    smoke: критические тесты для проверки базовой работоспособности
    regression: регрессионные тесты
